In [1]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."

In [1]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."

In [1]:
A = "안녕하세요 지금은 데이터 전처리 수업 시간입니다."

In [7]:
A[0:4]

'안녕하세'

In [6]:
A[0:9]

'안녕하세요 지금은'

In [8]:
A[-6:]

'시간입니다.'

In [12]:
A[-9:-7]

'수업'

In [22]:
A="I am {}"

In [20]:
B="jihye"

In [23]:
A.format(B)

'I am jihye'

In [24]:
print(("{}, {}").format(A,B))

I am {}, jihye


In [27]:
print(("{:.2f}, {:.3f}").format(3.1415,3.1415))

3.14, 3.142


In [39]:
url = "https://www.youtube.com/"
url = url.replace("youtube", "naver")
print(url)

https://www.naver.com/


In [40]:
A = [10,20,30,40,50,60,70,80,90]

In [42]:
A [0:4]

[10, 20, 30, 40]

In [43]:
A = ["독고영재, 50", "김철수, 30"]

In [44]:
A[0]

'독고영재, 50'

In [47]:
type(A)

list

In [48]:
type(A[0])

str

In [51]:
A[0][:4]

'독고영재'

In [54]:
A[1][-2:]

'30'

In [87]:
a=["독고영재, 50","김철수, 30"]
b=["김철수, 30", "김영희, 25"]

In [88]:
a[0][:a[0].index(",")]

'독고영재'

In [89]:
b[1][:b[1].index(",")]

'김영희'

In [90]:
a = ["hi", 10, "80", "김철수",50, 50.6]

In [93]:
a.append(100)

In [94]:
a

['hi', 10, '80', '김철수', 50, 50.6, 1, 100]

In [95]:
a.pop(1) #제거하고 싶든 값의 위치

10

In [96]:
a

['hi', '80', '김철수', 50, 50.6, 1, 100]

In [97]:
a.index(50)

3

In [98]:
a.pop(3)

50

In [99]:
a

['hi', '80', '김철수', 50.6, 1, 100]

In [104]:
import numpy as np
a=np.array([1,2,3,4])
a=np.append(a,[4,5])
a=np.insert(a,1,[7,8])

In [105]:
a=np.array([1,2,3,4,5])
a=np.delete(a,[1,3])

In [106]:
a=a[a<=4]

In [110]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
merged_array = np.vstack((array1, array2))
print(merged_array) #수직 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [111]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
merged_array = np.hstack((array1, array2))
print(merged_array) #수평

[[1 2 5 6]
 [3 4 7 8]]


In [1]:
A={1:"김철수", 20:"박영희"}

In [2]:
A[1]

'김철수'

In [3]:
A[20]

'박영희'

In [8]:
A.get(1)

'김철수'

In [9]:
A[3]

KeyError: 3

In [10]:
A.get(3) #none 값 출력

In [12]:
B={"1-A":"김철수", "20-b":"박영희"}

In [14]:
B["2-A"]="영희"

In [15]:
del B["20-b"]

In [16]:
A = {
    "1-A" : [1,2,3,4,5],
    "20-B" : ["A","B","C","D","E"]
}

In [47]:
A = [10,20,30,[1,2,3]]

In [27]:
print(A[3])

{1, 2, 3}


In [30]:
math_score = [20,30,40,50,60]
english_score = [50,70,50,60,90]

In [31]:
url = "https://www.youtube.com/"
url = url.replace("youtube", "naver")
print(url)

https://www.naver.com/


In [37]:
math_avg = sum(math_score)/len(math_score)
english_avg = sum(english_score)/len(math_score)
print("수학 점수 평균:", math_avg)
print("영어 점수 평균:", english_avg)

수학 점수 평균: 40.0
영어 점수 평균: 64.0


In [40]:
list = [1,2,100,4,5,900]
list.remove(100)
list.remove(900)

In [41]:
list

[1, 2, 4, 5]

In [42]:
score ={
    "math" : math_score,
    "english" : english_score
}

In [44]:
score = {
    "math" : [20,30,40,50,60],
    "english" : [50,70,50,60,90]
}

A = score["math"][0]+score["english"][2]
print(A)

70
